<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Operators.cs" Link="Operators.cs" />
    <Compile Include="..\switch.cs" Link="switch.cs" />
    <Compile Include="..\forloop.cs" Link="forloop.cs" />
    <Compile Include="..\foreach.cs" Link="foreach.cs" />
    <Compile Include="..\while.cs" Link="while.cs" />
    <Compile Include="..\TemperatureConverter.cs" Link="TemperatureConverter.cs" />
    <Compile Include="..\Tuples.cs" Link="Tuples.cs" />
    <Compile Include="..\Null.cs" Link="Null.cs" />
    <Compile Include="..\User.cs" Link="User.cs" />
    <Compile Include="..\assending.cs" Link="assending.cs" />
  </ItemGroup>

</Project>
